version: '3.4'

services:
    dotnet: 
        build: ./alpine_${TYPE_DOTNET}
        container_name: dotnet
        tty: true
        volumes:
            - ${APP_PATH}:/var/dotnet
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: mongo
        command: [--auth]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
            MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
        ports:
            - 27017:27017
        restart: always
    mongo-express:
        image: mongo-express:latest
        
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASS}
            ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGODB_DATABASE}
        depends_on:
            - mongo